version: '2.1'

networks:
  monitoring:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus:v2.2.0
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=30d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.14.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "9093:9093"
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox-exporter/config:/config
    command: --config.file=/config/blackbox.yml
    networks:
      - monitoring

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    depends_on:
      - prometheus
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.frontend.rule=Host:grafana.aws.mydomain.de"
    #   - "traefik.port=3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=vonage-status-panel
      # - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=s3
      # - GF_EXTERNAL_IMAGE_STORAGE_S3_BUCKET=funke-monitoring
      # - GF_EXTERNAL_IMAGE_STORAGE_S3_REGION=eu-central-1
      # - GF_EXTERNAL_IMAGE_STORAGE_S3_PATH=grafana_images
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitoring

  cloudwatch-exporter:
    image: prom/cloudwatch-exporter
    container_name: cloudwatch-exporter
    volumes:
      - ./cloudwatch-exporter/config.yml:/config/config.yml
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - "9106:9106"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor:v0.30.2
    container_name: cadvisor
    user: root
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/sys/fs/cgroup:ro
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - monitoring
