global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cloudwatch_exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
  - job_name: 'pushgateway'
    scrape_interval: 5s
# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'jmx-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['ip-10-102-67-123.eu-central-1.compute.internal:9404']
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
