{
 "title": "Ping Alerts - Server Status",
 "description": "Monitor and set alerts for all the pings to your servers using blackbox exporter and prometheus.",
 "tags": [
  "alerts",
  "linux",
  "windows"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(probe_success{job=\"blackbox\"}, instance) "
   }
  ]
 },
 "panels": [
  {
   "title": "Ping time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.92\",job=\"blackbox\"}",
     "legendFormat": "prod-db1"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.93\",job=\"blackbox\"}",
     "legendFormat": "prod-db2"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.95\",job=\"blackbox\"}",
     "legendFormat": "prod-db3"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.102\",job=\"blackbox\"}",
     "legendFormat": "prod-solr1"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.103\",job=\"blackbox\"}",
     "legendFormat": "prod-solr2"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.104\",job=\"blackbox\"}",
     "legendFormat": "prod-solr3"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.112\",job=\"blackbox\"}",
     "legendFormat": "prod-be1"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.113\",job=\"blackbox\"}",
     "legendFormat": "prod-be2"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.111\",job=\"blackbox\"}",
     "legendFormat": "prod-be4"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.33\",job=\"blackbox\"}",
     "legendFormat": "prod-fe1"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.34\",job=\"blackbox\"}",
     "legendFormat": "prod-fe2"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.35\",job=\"blackbox\"}",
     "legendFormat": "prod-fe3"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.38\",job=\"blackbox\"}",
     "legendFormat": "prod-fe4"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.67\",job=\"blackbox\"}",
     "legendFormat": "prod-fe5"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.68\",job=\"blackbox\"}",
     "legendFormat": "prod-fe6"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.70\",job=\"blackbox\"}",
     "legendFormat": "prod-fe7"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.71\",job=\"blackbox\"}",
     "legendFormat": "prod-fe8"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.74\",job=\"blackbox\"}",
     "legendFormat": "prod-fe9"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.76\",job=\"blackbox\"}",
     "legendFormat": "prod-fe10"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.77\",job=\"blackbox\"}",
     "legendFormat": "prod-fe11"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.79\",job=\"blackbox\"}",
     "legendFormat": "prod-fe12"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.82\",job=\"blackbox\"}",
     "legendFormat": "prod-fe13"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.43\",job=\"blackbox\"}",
     "legendFormat": "prod-web1"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.44\",job=\"blackbox\"}",
     "legendFormat": "prod-web2"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.45\",job=\"blackbox\"}",
     "legendFormat": "prod-web3"
    },
    {
     "expr": "probe_duration_seconds{instance=\"149.221.203.46\",job=\"blackbox\"}",
     "legendFormat": "prod-web4"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "OK" }
   ],
   "targets": [
    {
     "expr": "probe_success{instance=\"149.221.203.92\",job=\"blackbox\"}",
     "legendFormat": "prod-db1"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.93\",job=\"blackbox\"}",
     "legendFormat": "prod-db2"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.95\",job=\"blackbox\"}",
     "legendFormat": "prod-db3"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.102\",job=\"blackbox\"}",
     "legendFormat": "prod-solr1"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.103\",job=\"blackbox\"}",
     "legendFormat": "prod-solr2"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.104\",job=\"blackbox\"}",
     "legendFormat": "prod-solr3"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.112\",job=\"blackbox\"}",
     "legendFormat": "prod-be1"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.113\",job=\"blackbox\"}",
     "legendFormat": "prod-be2"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.111\",job=\"blackbox\"}",
     "legendFormat": "prod-be4"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.33\",job=\"blackbox\"}",
     "legendFormat": "prod-fe1"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.34\",job=\"blackbox\"}",
     "legendFormat": "prod-fe2"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.35\",job=\"blackbox\"}",
     "legendFormat": "prod-fe3"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.38\",job=\"blackbox\"}",
     "legendFormat": "prod-fe4"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.67\",job=\"blackbox\"}",
     "legendFormat": "prod-fe5"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.68\",job=\"blackbox\"}",
     "legendFormat": "prod-fe6"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.70\",job=\"blackbox\"}",
     "legendFormat": "prod-fe7"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.71\",job=\"blackbox\"}",
     "legendFormat": "prod-fe8"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.74\",job=\"blackbox\"}",
     "legendFormat": "prod-fe9"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.76\",job=\"blackbox\"}",
     "legendFormat": "prod-fe10"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.77\",job=\"blackbox\"}",
     "legendFormat": "prod-fe11"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.79\",job=\"blackbox\"}",
     "legendFormat": "prod-fe12"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.82\",job=\"blackbox\"}",
     "legendFormat": "prod-fe13"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.43\",job=\"blackbox\"}",
     "legendFormat": "prod-web1"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.44\",job=\"blackbox\"}",
     "legendFormat": "prod-web2"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.45\",job=\"blackbox\"}",
     "legendFormat": "prod-web3"
    },
    {
     "expr": "probe_success{instance=\"149.221.203.46\",job=\"blackbox\"}",
     "legendFormat": "prod-web4"
    }
   ]
  },
  {
   "title": "$node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "repeat": "node",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=~\"$node\"}"
    }
   ]
  }
 ]
}